-- Do not change this file
DELETE FROM STORES WHERE ID = 1;

DELETE FROM EMPLOYEE WHERE ID = 1050;

DELETE FROM CONTACT_INFO WHERE ID = 1050;

UPDATE GROCERY SET NEXT_EXPIRE_DATE = '3/3/2024' WHERE ID IN (8, 14, 17);

